-- Roll M7.5 storage changes back to the original unpartitioned delta table.

ALTER TABLE orderbook_deltas RENAME TO orderbook_deltas_partitioned;
ALTER TABLE orderbook_deltas_partitioned
    DROP CONSTRAINT orderbook_deltas_pkey;
DROP INDEX orderbook_deltas_input_offset_idx;
DROP INDEX orderbook_deltas_input_raw_event_idx;
DROP INDEX orderbook_deltas_group_event_time_idx;

CREATE TABLE orderbook_deltas
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id           text        NOT NULL,
    input_id           text        NOT NULL,

    event_time         timestamptz NOT NULL,
    exchange_time      timestamptz,
    local_receive_time timestamptz,

    raw_event_id       text,
    first_update_id    bigint,
    last_update_id     bigint,
    prev_update_id     bigint,
    sequence           bigint,

    bids               jsonb       NOT NULL DEFAULT '[]'::jsonb,
    asks               jsonb       NOT NULL DEFAULT '[]'::jsonb,

    kafka_topic        text        NOT NULL,
    kafka_partition    integer     NOT NULL,
    kafka_offset       bigint      NOT NULL,
    ingested_at        timestamptz NOT NULL DEFAULT now()
);

INSERT INTO orderbook_deltas
    (id, group_id, input_id, event_time, exchange_time, local_receive_time,
     raw_event_id, first_update_id, last_update_id, prev_update_id, sequence,
     bids, asks, kafka_topic, kafka_partition, kafka_offset, ingested_at)
OVERRIDING SYSTEM VALUE
SELECT
    id, group_id, input_id, event_time, exchange_time, local_receive_time,
    raw_event_id, first_update_id, last_update_id, prev_update_id, sequence,
    bids, asks, kafka_topic, kafka_partition, kafka_offset, ingested_at
FROM orderbook_deltas_partitioned;

SELECT setval(
    pg_get_serial_sequence('orderbook_deltas', 'id'),
    COALESCE((SELECT max(id) FROM orderbook_deltas), 1),
    EXISTS (SELECT 1 FROM orderbook_deltas)
);

CREATE UNIQUE INDEX orderbook_deltas_input_offset_uidx
    ON orderbook_deltas (input_id, kafka_partition, kafka_offset);
CREATE UNIQUE INDEX orderbook_deltas_input_raw_event_uidx
    ON orderbook_deltas (input_id, raw_event_id) WHERE raw_event_id IS NOT NULL;
CREATE INDEX orderbook_deltas_group_event_time_idx
    ON orderbook_deltas (group_id, event_time);

DROP TABLE orderbook_deltas_partitioned;
DROP TABLE orderbook_delta_partitions;
DROP TABLE stream_write_progress;
