-- M7.5: durable stream write progress and hourly order-book delta partitions.

CREATE TABLE stream_write_progress
(
    input_id          text        NOT NULL
        REFERENCES group_inputs (input_id) ON DELETE CASCADE,
    kafka_partition   integer     NOT NULL,
    durable_offset    bigint      NOT NULL,
    last_raw_event_id text,
    last_update_id    bigint,
    last_sequence     bigint,
    updated_at        timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (input_id, kafka_partition)
);

CREATE TABLE orderbook_delta_partitions
(
    partition_name text PRIMARY KEY,
    range_start    timestamptz NOT NULL,
    range_end      timestamptz NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),

    CHECK (range_end > range_start),
    UNIQUE (range_start, range_end)
);

ALTER TABLE orderbook_deltas RENAME TO orderbook_deltas_unpartitioned;
ALTER TABLE orderbook_deltas_unpartitioned
    DROP CONSTRAINT orderbook_deltas_pkey;
DROP INDEX orderbook_deltas_input_offset_uidx;
DROP INDEX orderbook_deltas_input_raw_event_uidx;
DROP INDEX orderbook_deltas_group_event_time_idx;

CREATE TABLE orderbook_deltas
(
    id                 bigint GENERATED BY DEFAULT AS IDENTITY,
    group_id           text        NOT NULL,
    input_id           text        NOT NULL,

    event_time         timestamptz NOT NULL,
    exchange_time      timestamptz,
    local_receive_time timestamptz,

    raw_event_id       text,
    first_update_id    bigint,
    last_update_id     bigint,
    prev_update_id     bigint,
    sequence           bigint,

    bids               jsonb       NOT NULL DEFAULT '[]'::jsonb,
    asks               jsonb       NOT NULL DEFAULT '[]'::jsonb,
    raw_payload        bytea       NOT NULL,

    kafka_topic        text        NOT NULL,
    kafka_partition    integer     NOT NULL,
    kafka_offset       bigint      NOT NULL,
    ingested_at        timestamptz NOT NULL DEFAULT now(),

    PRIMARY KEY (id, ingested_at)
) PARTITION BY RANGE (ingested_at);

CREATE INDEX orderbook_deltas_input_offset_idx
    ON orderbook_deltas (input_id, kafka_partition, kafka_offset);
CREATE INDEX orderbook_deltas_input_raw_event_idx
    ON orderbook_deltas (input_id, raw_event_id) WHERE raw_event_id IS NOT NULL;
CREATE INDEX orderbook_deltas_group_event_time_idx
    ON orderbook_deltas (group_id, event_time);

DO $$
DECLARE
    partition_start timestamptz;
    partition_end   timestamptz;
    partition_name  text;
BEGIN
    FOR partition_start IN
        SELECT DISTINCT date_trunc('hour', boundary)
        FROM (
            SELECT ingested_at AS boundary
            FROM orderbook_deltas_unpartitioned
            UNION ALL
            SELECT clock_timestamp() + make_interval(hours => n)
            FROM generate_series(0, 3) AS n
        ) boundaries
        ORDER BY 1
    LOOP
        partition_end := partition_start + interval '1 hour';
        partition_name := 'orderbook_deltas_' ||
            to_char(partition_start AT TIME ZONE 'UTC', 'YYYYMMDD_HH24');

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF orderbook_deltas ' ||
            'FOR VALUES FROM (%L) TO (%L)',
            partition_name, partition_start, partition_end
        );

        INSERT INTO orderbook_delta_partitions
            (partition_name, range_start, range_end)
        VALUES
            (partition_name, partition_start, partition_end)
        ON CONFLICT ON CONSTRAINT orderbook_delta_partitions_pkey DO NOTHING;
    END LOOP;
END
$$;

INSERT INTO orderbook_deltas
    (id, group_id, input_id, event_time, exchange_time, local_receive_time,
     raw_event_id, first_update_id, last_update_id, prev_update_id, sequence,
     bids, asks, raw_payload, kafka_topic, kafka_partition, kafka_offset,
     ingested_at)
OVERRIDING SYSTEM VALUE
SELECT
    id, group_id, input_id, event_time, exchange_time, local_receive_time,
    raw_event_id, first_update_id, last_update_id, prev_update_id, sequence,
    bids, asks, ''::bytea, kafka_topic, kafka_partition, kafka_offset,
    ingested_at
FROM orderbook_deltas_unpartitioned;

SELECT setval(
    pg_get_serial_sequence('orderbook_deltas', 'id'),
    COALESCE((SELECT max(id) FROM orderbook_deltas), 1),
    EXISTS (SELECT 1 FROM orderbook_deltas)
);

DROP TABLE orderbook_deltas_unpartitioned;
